WIP: Update security endpoint
hassio-addons/addon-docker-enabler pull request #2
Opened 2018-09-09 23:28 UTC by tjorim

# Proposed Changes

Supervisor 129 and up usesa different API endpoint.

## Related Issues

Closes #1.

### Remarks

Only tested with supervisor 129.

2018-09-09 23:46 UTC, tjorim commented
@frenck Should `$(hass.api.supervisor.info.version)` be put in double quotation marks? Seems to work like this anyway.

2018-09-10 05:58 UTC, frenck requested changes

2018-09-10 05:58 UTC, frenck commented on docker-enabler/rootfs/usr/bin/run.sh
> +if [[ $(hass.api.supervisor.info.version) -gt 128 ]]; then
There is no need to create backward compatibility for the Supervisor.
The Supervisor updates are pushed, so everybody will be on it within 24 hours.

2018-09-10 07:16 UTC, tjorim commented
Didn't think of that, cleaned it up.

2018-09-15 11:06 UTC, frenck approved these changes

2018-09-15 11:06 UTC, merged